### ISSUE TITLE
[OpenBSD/ld.bfd] (netgen|magic)exec wants GR_LIBS to link successfully

### ISSUE THREAD

**Issue by julianaito** [RTimothyEdwards/netgen#2]
Hi!

While netgen and magic builds properly with LLVM's lld on OpenBSD, our older GNU binutils ld.bfd [fails while linking netgenexec](http://build-failures.rhaalovely.net/powerpc/last/cad/netgen.log), because it's picky.

Note that magic is also impacted because they share the same build script.

Adding GR_LIBS to netgenexec lib flags does the job. I'm not sure it's the right thing to do, so i wanted to know you opinion about that.

(cc @just22 @kmosiejczuk)

```diff
--- tcltk/Makefile.orig
+++ tcltk/Makefile
@@ -25,7 +25,7 @@ install-tcl: netgenexec${EXEEXT} $(DESTDIR)${BINDIR}/n
 netgenexec${EXEEXT}: netgenexec.c
 	${CC} ${CFLAGS} ${CPPFLAGS} ${DFLAGS_NOSTUB} netgenexec.c \
 		-o netgenexec${EXEEXT} \
-		${LDFLAGS} ${LIBS} ${LIB_SPECS_NOSTUB}
+		${LIB_SPECS_NOSTUB} ${LDFLAGS} ${LIBS} ${GR_LIBS}
 
 netgen.tcl: netgen.tcl.in
 	sed -e 's%TCL_DIR%${TCLDIR}%g' \
```

**Comment by RTimothyEdwards** [comment]
For me, doing "ldd /usr/local/lib/netgen/tcl/netgenexec" shows that libX11 is linked to the file, so I assume that there is no harm in doing this.

**Comment by RTimothyEdwards** [comment]
Pushed fix to opencircuitdesign.com ;  this will be updated in github overnight.  I will close this tomorrow after the update.

**Comment by julianaito** [comment]
Thanks a lot! I'll provide a similar change for magic soon.
