### ISSUE TITLE
JSON LVS Report doesn't match the text LVS report

### ISSUE THREAD

**Issue by donn** [RTimothyEdwards/netgen#78]
Using 1efa054ac1302a2b8b03a41e90420fc055d5796e

The pin lists in the LVS text report and the JSON report are quite different:

![Screenshot at 2023-07-10 17:55:12](https://github.com/efabless/openlane2/assets/12652988/b3456633-cb71-4487-91d8-ab1c9fe825c0)

![Screenshot at 2023-07-10 17:55:40](https://github.com/efabless/openlane2/assets/12652988/f2351bd1-7b28-4811-8e10-109cce5fb670)
![Screenshot at 2023-07-10 17:55:46](https://github.com/efabless/openlane2/assets/12652988/791b2b45-b4b8-4727-929b-ba680650684c)

The JSON report is fine for the first three, then it breaks.

---

Reproducible:

[repro.tar.gz](https://github.com/RTimothyEdwards/netgen/files/12013623/repro.tar.gz)

To use it, set the `PDK_ROOT` environment variable appropriately then `sh run`.

**Comment by RTimothyEdwards** [comment]
Thanks for the test case.  Part of the pin matching routine had been modified and the Tcl list generation used to produce the JSON output was not correspondingly modified, so they ended up with a difference in opinion anywhere that ports were tied together.  This should be fixed now in netgen version 1.5.255.
