### ISSUE TITLE
False negative errors

### ISSUE THREAD

**Issue by marwaneltoukhy** [RTimothyEdwards/netgen#83]
I came across a false negative error that didn't show up in the LVS report. Not sure if this is the best place to file this issue.

**ISSUE:**
openframe example has a pico macro inside it, the GND on met5 wasn't connected from the top level to the macro because of an issue in PnR. This didn't show up as an open circuit in the LVS report, what I think happened is that the GND is shorted in the substrate layer, and because the macro didn't have a `subcut` layer around it, it wasn't caught in LVS. The error did show up when I ran soft checks, not the full transistor level LVS.

**REPRODUCIBLE**
Repo: https://github.com/efabless/caravel_openframe_project/commits/physical_views
branch: `physical_views`
commit: `9256ebd04c2eaa350f8b5d3f29834bba7256b1fc`

**Comment by RTimothyEdwards** [comment]
@d-m-bailey :  Thanks for the clarification, and I apologize for misrepresenting CVC.  The general gist of the response is still valid, though.
